spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxx
    username: 
    password:

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true #????????????
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
