spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

newebpay:
  merchant-id: ${NEWEBPAY_MERCHANTID}
  hash-key: ${NEWEBPAY_HASHKEY}
  hash-iv: ${NEWEBPAY_IV}
  #外部網址
  NOTIFY:  ${NEWEBPAY_NOTIFYURL}
  RETURN:  ${NEWEBPAT_RETURNURL}
  #回傳網址
  return-url: http://localhost:5173/payment/result
  version: 2.3
  logistics-completed-callback: ${NEWEBPAY_LOGISTICS_COMPLETED_NOTIFY}
  logistics-store-return: ${NEWEBPAT_LOGISTICS_STORE_RETURN}


aws:
  s3:
    bucket: ${AWS_S3_BUCKET}
    region: ${AWS_S3_REGION}
    access-key: ${AWS_S3_ACCESSKEY}
    secret-key: ${AWS_S3_SECRETKEY}

jwt:
  secret: ${JWT_SECRETKEY}

mybatis:
  configuration:
    map-underscore-to-camel-case: true


#logging:
#  level:
#    com:
#      yourproject:
#        mapper=DEBUG:


    #root: debug
#  file:
#    name: demo.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE} .%d{yyyy-MM-dd}.%i.gz
#      max-file-size: 1MB



#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true #????????????
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
