spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/e_shop
    username: eshop
    password: shop

newebpay:
  merchant-id: MS157560874
  hash-key: BsHdt4YNADlRYsLqmcYVSciU4qYjDh27
  hash-iv: CZb5CphRG1HivbuP
  #外部網址
  pay-url:  https://proleptical-unfastidiously-krissy.ngrok-free.dev/Api/Payment/notify
  #回傳網址
  return-url: http://localhost:5173/payment/result
  version: 2.3

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true #????????????
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL8Dialect
